apiVersion: v1
kind: Service
metadata:
  name: {{ include "test.service" . }}
  namespace: {{ include "test.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.webAppContainerPort }}
      name: test-http
  selector:
    {{ include "test.deploymentPods.labels" . | nindent 4 }}
