apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "test.serviceaccount" . }}
  labels:
    account: {{ include "test.serviceaccount" . }}
    app: {{ include "test.name" . }}
  namespace: {{ include "test.namespace" . }}